version: "3.9"

services:
  todo-sample:
    build:
      context: .
    container_name: todo-sample
    depends_on:
      - todo-sample-database
    ports:
      - "1234:1234"
    networks:
      - todo-sample-network

  todo-sample-database:
    image: postgres:alpine
    container_name: todo-sample-database
    environment:
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
      - POSTGRES_DB=todo-sample
    networks:
      - todo-sample-network


networks:
  todo-sample-network:
    driver: "bridge"
